# fly.toml app configuration file example
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fill these in with your own values
#app =
#primary_region =

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  # optional, avoids warnings on the free tier
  max_machines_running = 1
  processes = ["app"]
