name: ci

on: push

env:
  RELEASE_BRANCH: "refs/heads/main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/fabjan/smolservice
          tags: |
            type=raw,priority=900,value=v0.0.${{ github.run_number }},enable=${{ github.ref == env.RELEASE_BRANCH }}
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Check available platforms
        run: |
          echo ${{ steps.buildx.outputs.platforms }}
