name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fabjan/smolservice
            ghcr.io/fabjan/smolservice
          tags: |
            type=raw,value=v${{ env.GITHUB_RUN_NUMBER }}
            type=sha
            type=ref,event=branch
            type=ref,event=pr

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        if: github.ref == 'ref/head/master'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'ref/head/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
