name: ci

on: push

env:
  RELEASE_BRANCH: "refs/heads/main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/fabjan/smolservice
          tags: |
            type=raw,value=v0.0.${{ github.run_number }},enable=${{ github.ref == env.RELEASE_BRANCH }}
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=ref,event=pr

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and maybe push) container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == env.RELEASE_BRANCH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Write summary
        run: |
          echo "## Tags" >> $GITHUB_STEP_SUMMARY
          echo "$DOCKER_METADATA_OUTPUT_TAGS" | sed 's/^/- /g' >> $GITHUB_STEP_SUMMARY
